# Linked Micromap Plots via the **micromapST** R Package {#Ch3}


\chapterauthor{Linda Williams Pickle, James Blackwood Pearson, Jr., Daniel B. Carr}


Similar to Chapter \@ref(Ch2), the **micromapST**\index{R Packages!micromapST} R package [@CP2015CRAN],
accessible at https://cran.r-project.org/web/packages/micromapST/index.html,
will be introduced in this chapter. The reader will learn how to create a 
basic linked micromap plot\index{Linked micromap plot} via this R package. 
Although the default parameter settings give publication-ready output,
details will be provided on setting up additional labels and optional cumulative shading
which displays the growing geographic shading as one moves from the top to bottom
of the full plot.


## Introduction {#Ch3-Introduction}


As a reminder, see Chapter \@ref(Ch1) for general style requirements
for our `Micromap Plots in R` book. In particular, please do the following:

- Introduce meaningful labels for the sections, figures, and tables in your chapter.

- Create index entries for all R packages (such as the **micromap**\index{R Packages!micromap} R package)
and for all datasets (such as the _USstates_\index{Datasets!USstates} and _edPov_\index{Datasets!edPov} datasets)
that are used in your chapter.

- Include references for R packages and publications related to your chapter,
such as for the **micromap**\index{R Packages!micromap} [@PaOl2015] and 
**micromapST**\index{R Packages!micromapST} [@CP2015CRAN] R packages
and some micromap articles, book chapters, and books [@Carr2001;@SC2008;@CP2010].

- Also create index entries for main topics such as
linked micromap plots,\index{Linked micromap plot}
conditioned choropleth maps,\index{Conditioned choropleth map}
perceptual group,\index{Perceptual group}
color blindness,\index{Color blindness},
and quantile-quantile plot.\index{Quantile-quantile plot}


## Basic plot layout and function call {#Ch3-Basics}


Here goes the main content of your chapter. Introduce additional sections as needed.

## Display options {#Ch3-DisplayOpt}

In this section we illustrate some optional display options, such as cumultative shading, color choices,
enhanced labels and a vertical reference line. A reference is made to changing the number of rows per
perceptual group, to be illustrated in the next section.

## Using other built-in boundary files {#Ch3-OtherBoundaries}

In this section we plot the percent of residents with a bachelor's degree and residents living under 150%
of the federal poverty line in the state of Maryland by county.
First we show how to specify this boundary file (border group), then discuss the geographic patterns by county
and how poverty and education are negatively correlated, as expected. The default perceptual grouping for
Maryland's 24 counties (including Baltimore City) is 5-5-4-5-5.
Then we modify the plot to show how to specify the number of rows per perceptual group (e.g., 5-4-3-3-4-5) 
and discuss the suggested symmetric partitionings by Symanzik and Carr (2008; see book p.152 for full ref)
and comment on the practical limits of the display with respect to the number of perceptual groups and rows.

```{r Ch3-micromap1, fig.cap = 'Prevalence of covid-19 cases by U.S. state on 11/9/2020, as measured by the percentage of residents who knew someone with covid', fig.width = 7, fig.height = 9}

library(micromapST)

# Input data files.
# Data Set # 1
MDPovEd = read.csv('data/MDPovEducACSData20162020.csv',row.names=3)
head(MDPovEd)
panelDesc = data.frame(
  type=c('mapcum','id','dot','dot'),  
  lab1=c('','','% College','% Pov'),		
#  lab2=c('','','#','%'),
#  lab3=c('','','#','%'),
  col1=c(NA,NA,'PctBachDegree','PctLess150Pov')
 )


# ### sort by % college
#pdf(file='h://juergenmicromapbook//MDExamples//MDCollPov.pdf',width=7.5,height=10)
micromapST(MDPovEd,rowNames='id',panelDesc,sortVar='PctBachDegree',ascend=F,bordGrp='MarylandBG',
            plotNames='full',
            title=c('Maryland counties: % Living < 150% of Poverty Level and % with 4+ Years of College'))  
#dev.off()
```

## Discussion {#Ch3-Discussion}
Purposes and uses of the micromapST package to date

## Further Reading {#Ch3-FurtherReading}


Introduce cross-references to other chapters, e.g., Chapter \@ref(Ch1) and Chapter \@ref(Ch2),
where related work and further examples can be found in this book that match the content of this
chapter, that follow up on this chapter, or that are a prerequisite of this chapter.

Also, do some scientific literature review here that is specific to your chapter.
Where has this R package been introduced and used before, where have other plot types
or different countries been used in micromaps, what were other applications 
of micromaps that are related to the title and content of your chapter, etc.?


\printbibliography[segment=\therefsegment,heading=subbibliography]

