# Web-based Linked Micromap Plots (via Shiny) {#Ch7}


\chapterauthor{Marcus W. Beck}


Creating web-based interactive linked micromaps dates far back into the late 1990s. 
Early attempts were made via the Graphics Production Library (GPS). 
The National Cancer Institute (NCI) maintained a web page with interactive linked micromaps 
for its cancer data for more than ten years. Java versions also exist. 
This chapter will introduce the reader to the creation of linked micromap plots 
via the Shiny R package (https://shiny.rstudio.com/). 
A preliminary example of such a Shiny-based linked micromap plot can be 
accessed at https://beckmw.shinyapps.io/micromap_app/.


## Introduction {#Ch7-Introduction}


As a reminder, see Chapter \@ref(Ch1) for general style requirements
for our `Micromap Plots in R` book. In particular, please do the following:

- Introduce meaningful labels for the sections, figures, and tables in your chapter.

- Create index entries for all R packages (such as the **micromap**\index{R Packages!micromap} R package)
and for all datasets (such as the _USstates_\index{Datasets!USstates} and _edPov_\index{Datasets!edPov} datasets)
that are used in your chapter.

- Include references for R packages and publications related to your chapter,
such as for the **micromap**\index{R Packages!micromap} [@PaOl2015] and 
**micromapST**\index{R Packages!micromapST} [@CP2015CRAN] R packages
and some micromap articles, book chapters, and books [@Carr2001;@SC2008;@CP2010].

- Also create index entries for main topics such as
linked micromap plots,\index{Linked micromap plot}
conditioned choropleth maps,\index{Conditioned choropleth map}
perceptual group,\index{Perceptual group}
color blindness,\index{Color blindness},
and quantile-quantile plot.\index{Quantile-quantile plot}


## Main {#Ch7-Main}


Here goes the main content of your chapter. Introduce additional sections as needed.

For convenience, Figure \@ref(fig:Ch7-micromap1) shows one linked micromap plot\index{Linked micromap plot}
(which is the same as in Figure \@ref(fig:Ch1-micromap1)), but now formatted in a slightly more meaningful way.


```{r Ch7-micromap1, fig.cap = 'Here is a first micromap example for this chapter. Note that the figure is formatted in a slightly more meaningful way this time.', fig.width = 7, fig.height = 9}
library(micromap)

# initial example

data(USstates)
statePolys <- create_map_table(USstates, "ST")
data(edPov)

# basic figure 1
lmplot(
  stat.data = edPov,
  map.data = statePolys,
  panel.types = c("labels", "dot", "dot", "map"),
  panel.data = list("state", "pov", "ed", NA),
  ord.by = "pov",   
  grouping = 5, 
  median.row = TRUE,
  plot.width = 2, 
  plot.height = 6,
  map.link = c("StateAb", "ID")
)
```


## Further Reading {#Ch7-FurtherReading}


Introduce cross-references to other chapters, e.g., Chapter \@ref(Ch1) and Chapter \@ref(Ch2),
where related work and further examples can be found in this book that match the content of this
chapter, that follow up on this chapter, or that are a prerequisite of this chapter.

Also, do some scientific literature review here that is specific to your chapter.
Where has this R package been introduced and used before, where have other plot types
or different countries been used in micromaps, what were other applications 
of micromaps that are related to the title and content of your chapter, etc.?


\printbibliography[segment=\therefsegment,heading=subbibliography]

