# Conditioned Micromaps {#Ch8}


\chapterauthor{Brent D. Mast}


Conditioned micromaps, sometimes also called conditioned choropleth maps (CC maps) 
are the second of the three main variations of micromap visualizations. 
They allow an exploratory investigation of two explanatory variables 
and one response variable, usually in a geographic setting. 
The reader will learn how to create such conditioned micromaps and how to interpret them.


## Introduction {#Ch8-Introduction}


As a reminder, see Chapter \@ref(Ch1) for general style requirements
for our `Micromap Plots in R` book. In particular, please do the following:

- Introduce meaningful labels for the sections, figures, and tables in your chapter.

- Create index entries for all R packages (such as the **micromap**\index{R Packages!micromap} R package)
and for all datasets (such as the _USstates_\index{Datasets!USstates} and _edPov_\index{Datasets!edPov} datasets)
that are used in your chapter.

- Include references for R packages and publications related to your chapter,
such as for the **micromap**\index{R Packages!micromap} [@PaOl2015] and 
**micromapST**\index{R Packages!micromapST} [@CP2015CRAN] R packages
and some micromap articles, book chapters, and books [@Carr2001;@SC2008;@CP2010].

- Also create index entries for main topics such as
linked micromap plots,\index{Linked micromap plot}
conditioned choropleth maps,\index{Conditioned choropleth map}
perceptual group,\index{Perceptual group}
color blindness,\index{Color blindness},
and quantile-quantile plot.\index{Quantile-quantile plot}


## Main {#Ch8-Main}


Here goes the main content of your chapter. Introduce additional sections as needed.

For convenience, Figure \@ref(fig:Ch8-micromap1) shows one linked micromap plot\index{Linked micromap plot}
(which is the same as in Figure \@ref(fig:Ch1-micromap1)), but now formatted in a slightly more meaningful way.


```{r Ch8-micromap1, fig.cap = 'Trivial conditioned choropleth maps example based on the CCmaps() function from the maptools R package.', fig.width = 7, fig.height = 4}
# Based on code from the help page at
#  https://maptools.r-forge.r-project.org/reference/CCmaps.html

library(maptools)
library(lattice)

nc.sids <- readShapeSpatial(
  system.file("shapes/sids.shp",
    package = "maptools"
  )[1],
  IDvar = "FIPSNO",
  proj4string = CRS("+proj=longlat +ellps=clrk66")
)

nc.sids$ft.SID74 <- sqrt(1000) * (sqrt(nc.sids$SID74 / nc.sids$BIR74) +
  sqrt((nc.sids$SID74 + 1) / nc.sids$BIR74))
nc.sids$ft.NWBIR74 <- sqrt(1000) * (sqrt(nc.sids$NWBIR74 / nc.sids$BIR74) +
  sqrt((nc.sids$NWBIR74 + 1) / nc.sids$BIR74))

# sh_nw4 <- equal.count(nc.sids$ft.NWBIR74, number=4, overlap=1/5)
# CCmaps(nc.sids, "ft.SID74", list("Nonwhite_births"=sh_nw4),
#       col.regions=colorRampPalette(c("yellow1", "brown3"))(20),
#       main="Transformed SIDS rates 1974-8")

##

sh_nw4 <- equal.count(nc.sids$ft.NWBIR74, number = 3, overlap = 0)
sh_bir <- equal.count(nc.sids$BIR79, number = 3, overlap = 0)
CCmaps(
  obj = nc.sids,
  zcol = "ft.SID74",
  cvar = list(
    "Nonwhite_births" = sh_nw4,
    "Births79" = sh_bir
  ),
  col.regions = colorRampPalette(c("yellow1", "brown3"))(20),
  main = "Transformed SIDS rates 1974-78",
  layout = c(3, 3)
)
```


## Further Reading {#Ch8-FurtherReading}


Introduce cross-references to other chapters, e.g., Chapter \@ref(Ch1) and Chapter \@ref(Ch2),
where related work and further examples can be found in this book that match the content of this
chapter, that follow up on this chapter, or that are a prerequisite of this chapter.

Also, do some scientific literature review here that is specific to your chapter.
Where has this R package been introduced and used before, where have other plot types
or different countries been used in micromaps, what were other applications 
of micromaps that are related to the title and content of your chapter, etc.?


\printbibliography[segment=\therefsegment,heading=subbibliography]
