# Applications for the Environmental Field {#Ch11}


\chapterauthor{Michael G. McManus, Marcus W. Beck, J{\"u}rgen Symanzik}


This chapter will give the purpose and description of linked micromaps as applied to environmental data using the R package **micromap**\index{R Packages!micromap}.  We will ask what types of environmental data are most suited for summarizing and displaying as linked micromaps.  Additionally, we will show how linked micromaps can be used in spatial data analysis.  Our linked micromap examples are drawn from federal and state environmental agencies in the United States.

The purpose of a linked micromap is to show spatial locations corresponding to statistical estimates [@COCPC1998].  Linked micromaps simultaneously summarize and display both statistical and geographic distributions by linking statistical summaries of polygons, or areal units, to a series of small maps [@PMWOK2015JSS].  Implicit with this purpose and description is that space, defined as spatial contiguity of polygons, provides some context to the statistical estimates, and that the statistical estimates are representative of the polygons. That spatial context to statistical estimates can be one of three patterns:  spatial similarity among neighbors, spatial dissimilarity among neighbors, or no spatial pattern among neighbors.  


## Introduction {#Ch11-Introduction}


As a reminder, see Chapter \@ref(Ch1) for general style requirements
for our `Micromap Plots in R` book. In particular, please do the following:

- Introduce meaningful labels for the sections, figures, and tables in your chapter.

- Create index entries for all R packages (such as the **micromap**\index{R Packages!micromap} R package)
and for all datasets (such as the _USstates_\index{Datasets!USstates} and _edPov_\index{Datasets!edPov} datasets)
that are used in your chapter.

- Include references for R packages and publications related to your chapter,
such as for the **micromap**\index{R Packages!micromap} [@PaOl2015] and 
**micromapST**\index{R Packages!micromapST} [@CP2015CRAN] R packages
and some micromap articles, book chapters, and books [@Carr2001;@SC2008;@CP2010].

- Also create index entries for main topics such as
linked micromap plots,\index{Linked micromap plot}
conditioned choropleth maps,\index{Conditioned choropleth map}
perceptual group,\index{Perceptual group}
color blindness,\index{Color blindness},
and quantile-quantile plot.\index{Quantile-quantile plot}


## Main {#Ch11-Main}


Here goes the main content of your chapter. Introduce additional sections as needed.

For convenience, Figure \@ref(fig:Ch11-micromap1) shows one linked micromap plot\index{Linked micromap plot}
(which is the same as in Figure \@ref(fig:Ch1-micromap1)), but now formatted in a slightly more meaningful way.


```{r Ch11-micromap1, fig.cap = 'Here is a first micromap example for this chapter. Note that the figure is formatted in a slightly more meaningful way this time.', fig.width = 7, fig.height = 9}
library(micromap)

# initial example

data(USstates)
statePolys <- create_map_table(USstates, "ST")
data(edPov)

# basic figure 1
lmplot(
  stat.data = edPov,
  map.data = statePolys,
  panel.types = c("labels", "dot", "dot", "map"),
  panel.data = list("state", "pov", "ed", NA),
  ord.by = "pov",   
  grouping = 5, 
  median.row = TRUE,
  plot.width = 2, 
  plot.height = 6,
  map.link = c("StateAb", "ID")
)
```


## Further Reading {#Ch11-FurtherReading}


Introduce cross-references to other chapters, e.g., Chapter \@ref(Ch1) and Chapter \@ref(Ch2),
where related work and further examples can be found in this book that match the content of this
chapter, that follow up on this chapter, or that are a prerequisite of this chapter.

Also, do some scientific literature review here that is specific to your chapter.
Where has this R package been introduced and used before, where have other plot types
or different countries been used in micromaps, what were other applications 
of micromaps that are related to the title and content of your chapter, etc.?


\printbibliography[segment=\therefsegment,heading=subbibliography]

