# Applications for the Medical Field  {#Ch12}


\chapterauthor{Samson Y. Gebreab}


This chapter will focus on micromap applications from the medical field. 
Similar to the previous chapter, components from several of the previous chapters 
are revisited here, e.g., how to include non-standard geographic boundaries, e.g., 
health service areas, handle point locations, and deal with non-standard graph types 
such as scatterplots to emphasize on the relationship of two variables.


## Introduction {#Ch12-Introduction}


Visualization and disease mapping have long been part of medical field since John snow’s map of the Cholera Outbreak in London of 1854.  Snow drew dots on a map background which he subsequently used to trace the source of the cholera outbreak, i.e., fecal-contaminated water supplied by the Broad Street pump [@Snow1936]. His direct action in dismantling the pump saved many lives. However, since this investigation, advances in Geographic Information Systems (GIS), spatial statistical methods, coupled with developments in digital and computing resources, has led to a very powerful synergistic toolset that now supplies the means with which to effectively analyze and visualize any data that is spatially distributed. 

Over many years, many visualization tools have been developed to convert tabular information into visual graphs or plots (e.g. , @Carr1994a). Visualization tools offer a set of tools that can be used to simplify large and complex datasets into more comprehensible forms. Recent development in the field highlights the use of linked micromap (LM) plots [@CaPi1996]
as a way of displaying geographically indexed data. LM plots use multiple small maps (called micromaps) to visualize complex data structures in a geographical context. LM plots have already been used in many fields, including environmental science [@CaPi1996;@COPC1998;@SCAWWW1999], ecology [@COPC2000], epidemiology [@CWC2000;@SGGW2003ASA], and in the case of federal statistical summaries [@HSG2003].

History of LM plots in medical field:  application to birth defects data, Cardiovascular disease, Cancer, West Nile virus **(I will further expand this from literature review)**


The primary objective of this chapter is to demonstrate the applications of LM plots in presenting spatially and temporally indexed medical and health data. Specifically, it will describe the steps for generating various LM Plots and graph types (e.g., box plots, bar plots, scatter plots, and time series) using R programing language to summarize and visualize health outcomes and associated risk factors. This chapter will also provide examples of LM plots using non-standard geographic boundaries (e.g., census division). In conclusion, the chapter we will describe how LM plot can be a valuable tool to identify patterns, trends, relationships, and anomalies that were not at first obvious in the tables can be revealed quickly. Moreover, it will highlight the effectiveness of LM in communicating valuable medical information to the public and policy makers.


## Types of Medial Field Data {#Ch12-Types-Medical-Data}


## Applications of Linked Micromaps in Medical Field {#Ch12-Applications-Medical-Field}


### Classic Three-Column Linked Micromaps

- Data Source CDC: Age-standardized Cancer Mortality Rate FY2020, Smoking rate FY 2019, Poverty FY 2019
    -State Rates dots -classic three-Column Version with confidence interval)
-	Data Source: CVH, Stroke and CHD [@GDSMGD2015]


### Linked Micromaps with Bars and Boxplots

-	Data Source CDC: Age-standardized stroke death rates and annual percentage change by state  FY2000, and FY 2015 
    -State rates dots with confidence interval rates and bars for annual percentage change
-	Data Source CDC: Age-standardized heart Disease Mortality Data Among US Adults (35+) 
    -State rates dots with confidence interval rates, and county rates with boxplots 


### Time Series Linked Micromaps 

-	Data Source: CDC United States COVD-19 cases by state and time (Months: FY2020-2022)
    -Timeseries of COVID-19 Death by months (Jan- Dec), and  total cases dots with confidence interval  for FY 2020, FY2021, and FY2022


###	Linked Micromaps with Non-traditional Boundaries 

-	Data Source Gebreab et al published: Utah Birth defects  (classic three-Column Version with confidence interval)
-	Data Source CDC: Tobacco Use by US Census Division FY2018


## Concluding Remarks  {#Ch12-Concluding-Remarks}


The chapter illustrated the applications of LM plots in visualizing spatially indexed medical data. It demonstrated that LM plots can be valuable tools to graphically relate health outcomes and their associated demographic, social  and behavioral factors. Overall, the chapter highlighted that LM plots can be effective tools to identify geographic patterns, regional similarities, medically vulnerable populations, health outcomes, risk factors, trends, and the relationships between them **( I will further expand this).**



## Provided Template (To Be Deleted) {#Ch12-Template}


As a reminder, see Chapter \@ref(Ch1) for general style requirements
for our `Micromap Plots in R` book. In particular, please do the following:

- Introduce meaningful labels for the sections, figures, and tables in your chapter.

- Create index entries for all R packages (such as the **micromap**\index{R Packages!micromap} R package)
and for all datasets (such as the _USstates_\index{Datasets!USstates} and _edPov_\index{Datasets!edPov} datasets)
that are used in your chapter.

- Include references for R packages and publications related to your chapter,
such as for the **micromap**\index{R Packages!micromap} [@PaOl2015] and 
**micromapST**\index{R Packages!micromapST} [@CP2015CRAN] R packages
and some micromap articles, book chapters, and books [@Carr2001;@SC2008;@CP2010].

- Also create index entries for main topics such as
linked micromap plots,\index{Linked micromap plot}
conditioned choropleth maps,\index{Conditioned choropleth map}
perceptual group,\index{Perceptual group}
color blindness,\index{Color blindness},
and quantile-quantile plot.\index{Quantile-quantile plot}


## Main {#Ch12-Main}


Here goes the main content of your chapter. Introduce additional sections as needed.

For convenience, Figure \@ref(fig:Ch12-micromap1) shows one linked micromap plot\index{Linked micromap plot}
(which is the same as in Figure \@ref(fig:Ch1-micromap1)), but now formatted in a slightly more meaningful way.


```{r Ch12-micromap1, fig.cap = 'Here is a first micromap example for this chapter. Note that the figure is formatted in a slightly more meaningful way this time.', fig.width = 7, fig.height = 9}
library(micromap)

# initial example

data(USstates)
statePolys <- create_map_table(USstates, "ST")
data(edPov)

# basic figure 1
lmplot(
  stat.data = edPov,
  map.data = statePolys,
  panel.types = c("labels", "dot", "dot", "map"),
  panel.data = list("state", "pov", "ed", NA),
  ord.by = "pov",   
  grouping = 5, 
  median.row = TRUE,
  plot.width = 2, 
  plot.height = 6,
  map.link = c("StateAb", "ID")
)
```


## Further Reading {#Ch12-FurtherReading}


Introduce cross-references to other chapters, e.g., Chapter \@ref(Ch1) and Chapter \@ref(Ch2),
where related work and further examples can be found in this book that match the content of this
chapter, that follow up on this chapter, or that are a prerequisite of this chapter.

Also, do some scientific literature review here that is specific to your chapter.
Where has this R package been introduced and used before, where have other plot types
or different countries been used in micromaps, what were other applications 
of micromaps that are related to the title and content of your chapter, etc.?


\printbibliography[segment=\therefsegment,heading=subbibliography]

