\backmatter

`r if (knitr:::is_html_output()) '
# References {-}
'`

```{r Ch99-PackageReferences, include = FALSE}
# generate a BibTeX database automatically for some R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


## Micromap Reference Overview {#Ch99-MicromapReferenceOverview}


Here is an extended list of micromap references. A few more to come over the next few weeks.
Most of the underlying articles, book chapters, posters, etc. have been made available via a Box folder now.
You should have received an e-mail invitation to this Box folder on 3/25/2022.
If you did not receive such an invitation or cannot access the files,
please let me know.

This list should serve as a basic overview of what could be cited in various chapters of our book.
You have to decide yourselves what is most suitable for your chapter. Of course, bring in
additional references that are not listed yet. 

If possible work with the bibtex file `referencesMicromaps.bib` as the basis for your citations. 
Revisit Section \@ref(Ch1-CitationsReferences) how to do so (and see the examples below).

If you want to cite additional references, provide me with an initial bibtex entry,
provide me with the DOI of the article or book chapter, point me to the web page,
or provide me with any other way to construct a related bibtex entry.


- Ahn, Park, et al.:
@Ahn2013,
@Ahn2015,
@Ahn2016,
@AhPa2016,
@CHPA2014,
@Kim2015,
@PaAh2013,
@PaAh2014,
@PaAh2015Mortality,
@PaAh2015Climate,
@Park2016 (App at https://s2c-maps.shinyapps.io/home),


- Carr, Pickle, Bell, et al.:
@BHPW2006,
@OCCP1996,
@CaPi1996,
@COCPC1998,
@COPC1998,
@COPC2000,
@CWC2000,
@Carr2001,
@Carr2002,
@CaZh2002,
@CZL2002,
@CCBPZ2002,
@CBPZL2003,
@Carr2005,
@CWM2005,
@CP2010,
@CP2015CRAN,
@CCWS2006,
@Matthews2013 (Book Review),
@Heim2014,
@Kolvoord2010 (Book Review),
@LPC2017,
@PeCa2016CRAN,
@PeCa2022CRAN,
@PiCa2010,
@PPC2015JSS,
@Ugarte2012 (Book Review),
@Unwin2011 (Book Review),
@WCCBP2002,
@Zhang2012,
@ZhCa2014,
@ZPP2016,


- Mast et al.:
@Mast2013LinkedMicromaps,
@Mast2013CCmaps,
@Mast2014SpatialMismatch,
@Mast2014CompMMHomeownership,
@Mast2014CompMMTemporalDifferences,
@Mast2015,
@Mast2018,
@Mast2020,


- McManus, Payton, Weber, et al.:
@Beck2022 (Code at https://github.com/fawda123/micromap_app/tree/v2.0.0,
App at https://beckmw.shinyapps.io/micromap_app/),
@Griffith2014,
@MPRG2016,
@PWMO2012,
@PWMKO2013,
@PMWOK2015JSS,
@PaOl2015,
@PaOl2021,


- Symanzik et al.:
@Chapala2005,
@GGMS2008,
@Gebreab2010,
@GDSMGD2015,
@HPMCSGA2014,
@HPSCA2016,
@HSG2003,
@JoSy2001,
@LiSy2016ASA,
@Li2017,
@LiSy2017ASA,
@MPS2019ASA,
@Medri2021,
@PrSy2019,
@Probst2020,
@SWWCWA1998,
@SACWWW1999,
@SCAWWW1999,
@SyJo2001ASA,
@SHG2002ASA,
@SGGW2003ASA,
@Symanzik2004,
@SC2008,
@Symanzik2012,
@SC2013,
@Symanzik2014,
@SDWPM2014,
@SBDSS2016,
@SCMW2017,
@SLZSM2017ASA,
@Symanzik2021,
@Thapliyal2009,
@VoSy2011,
@Voge2012,
@Yarra2010,


- Others:
@Asado2014,
@Baulier2011,
@Blunt2006,
@BFLR2011,
@Cairo2013,
@DaWo2021,
@DrJo2011,
@Ellis2017,
@Everitt2021,
@FoWo2000,
@KIT2015,
@Kolb2015,
@LMV2017 (App at https://mandiluo.shinyapps.io/The_Indian_Story/),
@NPNA2019,
@SeSa2013,
@SFSHGSB2019,
@SWSCSS2018,
@SSK2007,
@TaSt2019,
@UtMo2010,
@VirginiaDEQ2020 (Code at https://github.com/EmmaVJones/ProbDash/tree/master/app,
App at https://evjones.shinyapps.io/FreshwaterProbMonEDA/),
@Wartenberg2009,
@Yu2021,


@RCore2022


Note: 126 micromap references found on Semantic Scholar on 3/23/2022 - see
https://www.semanticscholar.org/search?q=micromap&sort=relevance.
However, some of these references are related to
MicroMAPS (Microprocessor-based Measurement of Air Pollution from Satellite).


\printbibliography[segment=\therefsegment,heading=subbibliography]

